name: C/C++ CI


#Event ex: lors d'un "PUSH" sur la branche "MAIN" les tests sont runs/lors d'un "PULL REQUEST" sur la branch "MAIN" les tests sont runs
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3 #actions est l'endroit ou les tests sont runs, github.com/actions/checkout
    - name: make
      run: make
